#Display a listing of the resource
GET http://localhost:8000/api/v1/formal-types
Content-Type: application/json
###

#Display a listing by uuid.
GET http://localhost:8000/api/v1/formal-types/575b2d89-cf9e-4c1f-8fd1-6a0499ad4a4c
Content-Type: application/json
###

#Display a listing page of the resource
GET http://localhost:8000/api/v1/formal-types/page
Content-Type: application/json
###

#Store a newly created resource in storage.
POST http://localhost:8000/api/v1/formal-types
Content-Type: application/json

{
  "user_id": "575b2d89-cf9e-4c1f-8fd1-6a0499ad4a4c",
  "nif": "1233"
}
###

#Update the specified resource in storage.
PUT http://localhost:8000/api/v1/formal-types/09d9827b-b15c-430b-94bc-fd2685aa5396
Content-Type: application/json

{
  "nif": "1237722383",
  "name": "Maraia",
  "whatsapp": "952000000",
  "website": "https://site.com"
}
###

#Remove the specified resource from storage.
DELETE  http://localhost:8000/api/v1/formal-types/09d9827b-b15c-430b-94bc-fd2685aa5396
Content-Type: application/json
###
