services:
    tubkair:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "9000:9000"
        networks:
            - laravel
        depends_on:
             - redis

    redis:
        image: redis:alpine
        container_name: redis_server
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:

