services:
    tudkabir:
        build:
            context: .
            dockerfile: Dockerfile
        image: tudkabir_image
        container_name: tudkabir_container
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        env_file:
            - .env
        ports:
            - "9000:9000"
        depends_on:
            - redis

    redis:
        image: redis:alpine
        container_name: redis_container
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    dbdata:


# ghcr.io/incipient-nodejs/tudkabir:latest